version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/comments
      - REDIS_URL=redis://redis:6379
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=comments
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
